//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int idBooking { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idService { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateBooking { get; set; }
        public Nullable<System.DateTime> dateAddBooking { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
